version: '3'
services:
  nginx:
    image: nginx:1.15.8@sha256:b543f6d0983fbc25b9874e22f4fe257a567111da96fd1d8f1b44315f1236398c
    restart: unless-stopped
    volumes:
      # - ./htpasswd:/etc/nginx/.htpasswd
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  owncast:
    image: gabekangas/owncast:latest
    restart: unless-stopped
    volumes:
      - ./owncast.yaml:/app/config.yaml
    command: /app/owncast -configFile=config.yaml
    ports:
      - "1935:1935"
    expose:
      - 8080
    links:
      - "nginx"
